-- This file is for use with Corona Game Edition
--
-- This file is automatically generated with PhysicsEdtior (http://physicseditor.de). Do not edit
--
-- Usage example:
--			local scaleFactor = 1.0
--			local physicsData = (require "shapedefs").physicsData(scaleFactor)
--			local shape = display.newImage("objectname.png")
--			physics.addBody( shape, physicsData:get("objectname") )
--

-- copy needed functions to local scope
local unpack = unpack
local pairs = pairs
local ipairs = ipairs

module(...)

function physicsData(scale)
	local physics = { data =
	{ 
		
		["windows_icon"] = {
			
				{
					density = 2, friction = 0, bounce = 0, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   6.5, -31  ,  -38.5, -10  ,  -31.5, -34  ,  -15, -43.5  ,  -7, -43.5  ,  5, -38.5  ,  7.5, -35  }
				}  ,
				{
					density = 2, friction = 0, bounce = 0, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   -10.5, 30  ,  37.5, 8  ,  31.5, 30  ,  25, 40.5  ,  3, 42.5  ,  -9, 37.5  }
				}  ,
				{
					density = 2, friction = 0, bounce = 0, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   24, -28.5  ,  41.5, -4  ,  35, 4.5  ,  -36, -4.5  ,  -38.5, -10  ,  12, -33.5  }
				}  ,
				{
					density = 2, friction = 0, bounce = 0, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   -26, 28.5  ,  -42.5, 4  ,  -36, -4.5  ,  -10.5, 30  ,  -13.5, 33  }
				}  ,
				{
					density = 2, friction = 0, bounce = 0, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   -15, -43.5  ,  -31.5, -34  ,  -28, -39.5  }
				}  ,
				{
					density = 2, friction = 0, bounce = 0, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   41.5, -4  ,  24, -28.5  ,  42, -31.5  ,  47.5, -30  }
				}  ,
				{
					density = 2, friction = 0, bounce = 0, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   -48.5, 28  ,  -42.5, 4  ,  -26, 28.5  ,  -46, 31.5  }
				}  ,
				{
					density = 2, friction = 0, bounce = 0, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   -36, -4.5  ,  35, 4.5  ,  37.5, 8  ,  -10.5, 30  }
				}  
		}
		
		, 
		["apple_icon"] = {
			
				{
					density = 2, friction = 0, bounce = 0, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   32.5, 2.5  ,  -4, -29  ,  15, -34  ,  31, -32  ,  44, -21  }
				}  ,
				{
					density = 2, friction = 0, bounce = 0, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   -32.5, 46.5  ,  -42, 32  ,  -48.5, 11.5  ,  -15, -33  ,  36.5, 16.5  ,  47.5, 29.5  ,  1, 53  ,  -19, 57  }
				}  ,
				{
					density = 2, friction = 0, bounce = 0, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   23.5, -49.5  ,  15, -34  ,  -4, -29  ,  3.5, -49.5  ,  17, -58  ,  21.5, -56.5  }
				}  ,
				{
					density = 2, friction = 0, bounce = 0, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   18, 57  ,  1, 53  ,  47.5, 29.5  ,  36.5, 48.5  ,  28.5, 55.5  }
				}  ,
				{
					density = 2, friction = 0, bounce = 0, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   -15, -33  ,  -48.5, 11.5  ,  -47.5, -8.5  ,  -40.5, -22.5  ,  -30.5, -30.5  }
				}  ,
				{
					density = 2, friction = 0, bounce = 0, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   47.5, 29.5  ,  36.5, 16.5  ,  46.5, 24.5  }
				}  ,
				{
					density = 2, friction = 0, bounce = 0, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   36.5, 16.5  ,  -15, -33  ,  -4, -29  ,  32.5, 2.5  }
				}  
		}
		
		, 
		["gates_player"] = {
			
				{
					density = 2, friction = 0, bounce = 0, isSensor=true, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   137, -65  ,  139.5, -41.5  ,  127.5, 1.5  ,  112, -56  ,  115, -77  }
				}  ,
				{
					density = 2, friction = 0, bounce = 0, isSensor=true, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   112, -56  ,  127.5, 1.5  ,  92, -60  ,  94.5, -70.5  }
				}  ,
				{
					density = 2, friction = 0, bounce = 0, isSensor=true, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   -93.5, -76.5  ,  -116.5, -42.5  ,  -119.5, -76.5  ,  -115, -87  }
				}  ,
				{
					density = 2, friction = 0, bounce = 0, isSensor=true, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   -71, -70  ,  -111, 139  ,  -150.5, 83.5  ,  -116.5, -42.5  ,  -93.5, -76.5  ,  -84, -81  }
				}  ,
				{
					density = 2, friction = 0, bounce = 0, isSensor=true, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   -150.5, 83.5  ,  -111, 139  ,  -142.5, 117.5  }
				}  ,
				{
					density = 2, friction = 0, bounce = 0, isSensor=true, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   58.5, -149.5  ,  39.5, -78.5  ,  -36.5, -102.5  ,  -56.5, -143.5  ,  -51.5, -172.5  ,  -24, -208  ,  6, -215  ,  43.5, -191.5  }
				}  ,
				{
					density = 2, friction = 0, bounce = 0, isSensor=true, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   -111, 139  ,  -71, -70  ,  -50.5, -77.5  ,  94.5, 132.5  ,  -99.5, 173.5  ,  -112.5, 156.5  }
				}  ,
				{
					density = 2, friction = 0, bounce = 0, isSensor=true, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   94.5, 132.5  ,  -50.5, -77.5  ,  -36.5, -102.5  ,  92, -60  ,  127.5, 1.5  ,  148.5, 85.5  ,  125.5, 123.5  }
				}  ,
				{
					density = 2, friction = 0, bounce = 0, isSensor=true, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   -99.5, 173.5  ,  95, 187  ,  101, 219  ,  -109, 219  }
				}  ,
				{
					density = 2, friction = 0, bounce = 0, isSensor=true, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   95, 187  ,  -99.5, 173.5  ,  94.5, 132.5  ,  102.5, 166.5  }
				}  
		}
		
		, 
		["jobs_player"] = {
			
				{
					density = 2, friction = 0, bounce = 0, isSensor=true, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   -92.5, -6.5  ,  -95, 41  ,  -117, 1  ,  -107, -19  ,  -98, -20  }
				}  ,
				{
					density = 2, friction = 0, bounce = 0, isSensor=true, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   -44.5, 153.5  ,  107.5, 176.5  ,  115, 219  ,  -65, 219  }
				}  ,
				{
					density = 2, friction = 0, bounce = 0, isSensor=true, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   -98.5, 109.5  ,  -142, 19  ,  -95, 41  ,  -49.5, 119.5  ,  -81.5, 122.5  }
				}  ,
				{
					density = 2, friction = 0, bounce = 0, isSensor=true, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   10, -200  ,  39, -214  ,  71, -105  ,  7.5, -91.5  ,  -5.5, -122.5  ,  -9.5, -164.5  }
				}  ,
				{
					density = 2, friction = 0, bounce = 0, isSensor=true, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   -127.5, -2.5  ,  -142, 19  ,  -146.5, -14.5  ,  -141.5, -18.5  }
				}  ,
				{
					density = 2, friction = 0, bounce = 0, isSensor=true, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   -117, 1  ,  -95, 41  ,  -142, 19  ,  -127.5, -2.5  }
				}  ,
				{
					density = 2, friction = 0, bounce = 0, isSensor=true, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   82.5, -184.5  ,  88.5, -154.5  ,  71, -105  ,  39, -214  ,  64, -206  }
				}  ,
				{
					density = 2, friction = 0, bounce = 0, isSensor=true, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   -44.5, 153.5  ,  -49.5, 119.5  ,  7.5, -91.5  ,  129.5, -53.5  ,  140.5, -26.5  ,  138.5, 93.5  ,  107.5, 176.5  }
				}  ,
				{
					density = 2, friction = 0, bounce = 0, isSensor=true, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   -46, -60  ,  7.5, -91.5  ,  -49.5, 119.5  ,  -95, 41  }
				}  ,
				{
					density = 2, friction = 0, bounce = 0, isSensor=true, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   39, -214  ,  10, -200  ,  24, -211  }
				}  ,
				{
					density = 2, friction = 0, bounce = 0, isSensor=true, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   129.5, -53.5  ,  7.5, -91.5  ,  71, -105  }
				}  
		}
		
	} }

	-- apply scale factor
	local s = scale or 1.0
	for bi,body in pairs(physics.data) do
		for fi,fixture in ipairs(body) do
			for ci,coordinate in ipairs(fixture.shape) do
				fixture.shape[ci] = s * coordinate
			end
		end
	end
	
	function physics:get(name)
		return unpack(self.data[name])
	end
	
	return physics;
end


